### ISSUE TITLE
Past version of Isabelle seems an error in README

### ISSUE THREAD

**Issue by Yosuke-Ito-345** [data61/PSL#217]
The description of the section Smart_Isabelle in README
"Past versions of Isabelle, such as Isabelle2023, are no longer supported."
seems wrong.
Is the following correct?
"Past versions of Isabelle, such as Isabelle2022, are no longer supported."
Sorry if I misunderstand what you mean.

**Comment by yutakang** [comment]
Good catch! You are correct, we currently support only Isabelle2023. I'm also pleased to see that someone has visited this repository. Thanks!

**Comment by yutakang** [comment]
Fixed in https://github.com/data61/PSL/commit/db661365afd4bec1cb5736f3bb48609558b16d4a.
